name: Run Go Tests

on:
  push:
    branches:
      - main # Or 'master' if that is your main branch
  pull_request:
    branches:
      - main # Or 'master'

jobs:
  build:
    uses: matt-riley/matt-riley-ci/.github/workflows/go-ci.yml@098848d01b058526398113ee20eccadf30f4b881 # v1.9.2
    with:
      go-version-file: go.mod
      run-fmt: true
